name: Build Toolchain

on:
  workflow_dispatch:

env:
  GITHUB_EMAIL: ${{ secrets.EMAIL }}
  GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
  GITHUB_USER: ${{ secrets.USERNAME }}
  BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nurfaizfy/ubuntu:clang
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build LLVM
      run: bash ci.sh llvm
    - name: Build binutils
      run: bash ci.sh binutils
    - name: Upload build
      run: bash ci.sh upload
